/*
 * RCC.h
 *
 *  Created on: 26 Apr 2022
 *      Author: Bunyamin
 */

#ifndef INC_RCC_H_
#define INC_RCC_H_

#include "stm32f767xx.h"

/*
 *  RCC Peripherals Clocks Control Macro Function Definition
 */

#define RCC_GPIOA_CLK_ENABLE()		SET_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOAEN);

#define RCC_GPIOB_CLK_ENABLE()		SET_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOBEN);

#define RCC_GPIOC_CLK_ENABLE()		SET_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOCEN);

#define RCC_GPIOD_CLK_ENABLE()		SET_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIODEN);

#define RCC_GPIOE_CLK_ENABLE()		SET_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOEEN);


#define RCC_GPIOA_CLK_DISABLE()     CLEAR_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOAEN);

#define RCC_GPIOB_CLK_DISABLE()     CLEAR_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOBEN);

#define RCC_GPIOC_CLK_DISABLE()     CLEAR_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOCEN);

#define RCC_GPIOD_CLK_DISABLE()     CLEAR_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIODEN);

#define RCC_GPIOE_CLK_DISABLE()     CLEAR_BITS(RCC->RCC_AHB1ENR,RCC_AHB1_GPIOEEN);




#endif /* INC_RCC_H_ */
