/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f767xx.h"

int main(void)
{
	RCC_GPIOA_CLK_ENABLE();
	RCC_GPIOB_CLK_ENABLE();
	RCC_GPIOC_CLK_ENABLE();
	RCC_GPIOD_CLK_ENABLE();
	RCC_GPIOE_CLK_ENABLE();

	RCC_GPIOA_CLK_DISABLE();
	RCC_GPIOB_CLK_DISABLE();
	RCC_GPIOC_CLK_DISABLE();
	RCC_GPIOD_CLK_DISABLE();
	RCC_GPIOE_CLK_DISABLE();
	for(;;);
}
