/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f767xx.h"
#include "GPIO.h"

static void GPIO_LedConfig();

int main(void)
{
	GPIO_LedConfig();

	//GPIO_WritePin(GPIOB,GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14, GPIO_PIN_SET);

	GPIO_Toggle(GPIOB, GPIO_PIN_14);


	for(;;);
}

static void GPIO_LedConfig(){

	RCC_GPIOB_CLK_ENABLE();

	GPIO_InitTypeDef_t GPIO_Led = {0};
	GPIO_Led.pinNumber = GPIO_PIN_0 | GPIO_PIN_7 | GPIO_PIN_14;
	GPIO_Led.Mode = GPIO_MODE_OUTPUT;
	GPIO_Led.Speed = SPEED_LOW;
	GPIO_Led.Otype = OTYPE_PP;
	GPIO_Led.PuPd = PUPD_NOPULL;

	GPIO_Init(GPIOB, &GPIO_Led);

}

